insert into Especialidade (nome, categoria) values
	('Alívio da Fome','ADRA'),
	('Avaliação da Comunidade','ADRA'),
	('Serviço Comunitário','ADRA'),
	('Resposta a Emergências e Desastres','ADRA'),
	('Resposta a Emergências e Desastres - avançado','ADRA'),
	('Alfabetização','ADRA'),
	('Resolução de Conflitos','ADRA'),
	('Reassentamento de Refugiados','ADRA'),
	('Desenvolvimento Comunitário','ADRA'),
	('Aeromodelismo','Artes e Habilidades Manuais'),
	('Apitos','Artes e Habilidades Manuais'),
	('Apitos - avançado','Artes e Habilidades Manuais'),
	('Arte com Barbante','Artes e Habilidades Manuais'),
	('Arte de Fazer Esteiras','Artes e Habilidades Manuais'),
	('Arte de Oleiro','Artes e Habilidades Manuais'),
	('Arte de Trançar','Artes e Habilidades Manuais'),
	('Arte de Trançar - avançado','Artes e Habilidades Manuais'),
	('Automodelismo','Artes e Habilidades Manuais'),
	('Balões de Ar Quente','Artes e Habilidades Manuais'),
	('Biscuit','Artes e Habilidades Manuais'),
	('Bordado em Ponto Cruz','Artes e Habilidades Manuais'),
	('Cerâmica','Artes e Habilidades Manuais'),
	('Cestaria','Artes e Habilidades Manuais'),
	('Construção Nativa','Artes e Habilidades Manuais'),
	('Corrida de Carrinhos de Madeira','Artes e Habilidades Manuais'),
	('Corrida de Carrinhos de Madeira - avançado','Artes e Habilidades Manuais'),
	('Crochê','Artes e Habilidades Manuais'),
	('Crochê - avançado','Artes e Habilidades Manuais'),
	('Cultura Indígena','Artes e Habilidades Manuais'),
	('Cultura Indígena - avançado','Artes e Habilidades Manuais'),
	('Decoração de Bolos','Artes e Habilidades Manuais'),
	('Decoupage','Artes e Habilidades Manuais'),
	('Desenho e Pintura','Artes e Habilidades Manuais'),
	('Desenho vetorial','Artes e Habilidades Manuais'),
	('E.V.A.','Artes e Habilidades Manuais'),
	('Embalagem','Artes e Habilidades Manuais'),
	('Entalhe em Madeira','Artes e Habilidades Manuais'),
	('Escultura','Artes e Habilidades Manuais'),
	('Esmaltado em Cobre','Artes e Habilidades Manuais'),
	('Esmaltado em Cobre - avançado','Artes e Habilidades Manuais'),
	('Espaçomodelismo','Artes e Habilidades Manuais'),
	('Espaçomodelismo - avançado','Artes e Habilidades Manuais'),
	('Estofamento','Artes e Habilidades Manuais'),
	('Fabricação de Velas','Artes e Habilidades Manuais'),
	('Faróis','Artes e Habilidades Manuais'),
	('Faróis - avançado','Artes e Habilidades Manuais'),
	('Ferreomodelismo','Artes e Habilidades Manuais'),
	('Fotografia Digital','Artes e Habilidades Manuais'),
	('Fuxico','Artes e Habilidades Manuais'),
	('Genealogia','Artes e Habilidades Manuais'),
	('Gravuras em Vidro','Artes e Habilidades Manuais'),
	('Herança Cultural','Artes e Habilidades Manuais'),
	('História em Quadrinhos','Artes e Habilidades Manuais'),
	('Lapidação','Artes e Habilidades Manuais'),
	('Letreiros e Cartazes','Artes e Habilidades Manuais'),
	('Macramê','Artes e Habilidades Manuais'),
	('Modelagem em Gesso','Artes e Habilidades Manuais'),
	('Modelagem e Fabricação de Sabão','Artes e Habilidades Manuais'),
	('Modelagem e Fabricação de Sabão - avançado','Artes e Habilidades Manuais'),
	('Música - avançado','Artes e Habilidades Manuais'),
	('Música - básico','Artes e Habilidades Manuais'),
	('Música - intermediário','Artes e Habilidades Manuais'),
	('Nautimodelismo','Artes e Habilidades Manuais'),
	('Origami','Artes e Habilidades Manuais'),
	('Origami - avançado','Artes e Habilidades Manuais'),
	('Ornamentação','Artes e Habilidades Manuais'),
	('Ornamentação com Flores','Artes e Habilidades Manuais'),
	('Papel Machê','Artes e Habilidades Manuais'),
	('Papercraft','Artes e Habilidades Manuais'),
	('Patchwork','Artes e Habilidades Manuais'),
	('Pintura em Tecido','Artes e Habilidades Manuais'),
	('Pintura em Vidro','Artes e Habilidades Manuais'),
	('Pirografia','Artes e Habilidades Manuais'),
	('Plástico Canvas','Artes e Habilidades Manuais'),
	('Plastimodelismo','Artes e Habilidades Manuais'),
	('Quilling','Artes e Habilidades Manuais'),
	('Quilling - avançado','Artes e Habilidades Manuais'),
	('Scrapbooking','Artes e Habilidades Manuais'),
	('Scrapbooking - avançado','Artes e Habilidades Manuais'),
	('Serigrafia','Artes e Habilidades Manuais'),
	('Serigrafia - avançado','Artes e Habilidades Manuais'),
	('Tecelagem','Artes e Habilidades Manuais'),
	('Telhados','Artes e Habilidades Manuais'),
	('Tie-dye','Artes e Habilidades Manuais'),
	('Trabalhos com Agulha','Artes e Habilidades Manuais'),
	('Trabalhos em Acrílico','Artes e Habilidades Manuais'),
	('Trabalhos em Couro','Artes e Habilidades Manuais'),
	('Trabalhos em Couro - avançado','Artes e Habilidades Manuais'),
	('Trabalhos em Feltro','Artes e Habilidades Manuais'),
	('Trabalhos em Madeira','Artes e Habilidades Manuais'),
	('Trabalhos em Metal','Artes e Habilidades Manuais'),
	('Trabalhos em Vidro','Artes e Habilidades Manuais'),
	('Tricô','Artes e Habilidades Manuais'),
	('Tricô - avançado','Artes e Habilidades Manuais'),
	('Violão','Artes e Habilidades Manuais'),
	('Violão - avançado','Artes e Habilidades Manuais'),
	('Xilogravura','Artes e Habilidades Manuais'),
	('Agricultura','Atividades Agrícolas'),
	('Agricultura Familiar de Subsistência','Atividades Agrícolas'),
	('Apicultura','Atividades Agrícolas'),
	('Avicultura','Atividades Agrícolas'),
	('Criação de Cabras','Atividades Agrícolas'),
	('Criação de Cavalos','Atividades Agrícolas'),
	('Criação de Gado Leiteiro','Atividades Agrícolas'),
	('Criação de Ovelhas','Atividades Agrícolas'),
	('Criação de Pombos','Atividades Agrícolas'),
	('Floricultura','Atividades Agrícolas'),
	('Jardinagem e Horticultura','Atividades Agrícolas'),
	('Pecuária','Atividades Agrícolas'),
	('Pescaria','Atividades Agrícolas'),
	('Pomicultura','Atividades Agrícolas'),
	('Pomicultura II - Frutas Pequenas','Atividades Agrícolas'),
	('Adoração Cristã','Missionárias e Comunitárias'),
	('Apocalipse','Missionárias e Comunitárias'),
	('Arqueologia Bíblica','Missionárias e Comunitárias'),
	('Arte da Pregação Cristã','Missionárias e Comunitárias'),
	('Arte da Pregação Cristã - avançado','Missionárias e Comunitárias'),
	('Arte de Contar Histórias Cristãs','Missionárias e Comunitárias'),
	('Arte em Fantoches','Missionárias e Comunitárias'),
	('Arte em Fantoches - avançado','Missionárias e Comunitárias'),
	('Asseio e Cortesia Cristã','Missionárias e Comunitárias'),
	('Aventuras com Cristo','Missionárias e Comunitárias'),
	('Aventuras com Cristo - avançado','Missionárias e Comunitárias'),
	('Boa Conduta Escolar','Missionárias e Comunitárias'),
	('Braile','Missionárias e Comunitárias'),
	('Cerimônias','Missionárias e Comunitárias'),
	('Cidadania Cristã','Missionárias e Comunitárias'),
	('Colportagem','Missionárias e Comunitárias'),
	('Criacionismo','Missionárias e Comunitárias'),
	('Criacionismo - avançado','Missionárias e Comunitárias'),
	('Cultura Sul Americana','Missionárias e Comunitárias'),
	('Desfile com Carros Alegóricos','Missionárias e Comunitárias'),
	('Desfile com Carros Alegóricos - avançado','Missionárias e Comunitárias'),
	('Dramatização Cristã','Missionárias e Comunitárias'),
	('Escatologia','Missionárias e Comunitárias'),
	('Espírito de Profecia','Missionárias e Comunitárias'),
	('Estudo de Línguas','Missionárias e Comunitárias'),
	('Etnologia Missionária','Missionárias e Comunitárias'),
	('Evangelismo Pessoal','Missionárias e Comunitárias'),
	('Evangelismo Web','Missionárias e Comunitárias'),
	('Evangelismo Web - avançado','Missionárias e Comunitárias'),
	('Historiador Eclesiástico','Missionárias e Comunitárias'),
	('Intercessor','Missionárias e Comunitárias'),
	('Investigador Bíblico I','Missionárias e Comunitárias'),
	('Liderança Juvenil','Missionárias e Comunitárias'),
	('Língua de Sinais','Missionárias e Comunitárias'),
	('Língua de sinais - avançado','Missionárias e Comunitárias'),
	('Marcação Bíblica','Missionárias e Comunitárias'),
	('Marcação Bíblica - avançado','Missionárias e Comunitárias'),
	('Mensageira de Deus','Missionárias e Comunitárias'),
	('Mordomia','Missionárias e Comunitárias'),
	('Pacificador','Missionárias e Comunitárias'),
	('Pacificador - avançado','Missionárias e Comunitárias'),
	('Patriotismo','Missionárias e Comunitárias'),
	('Pioneiros Adventistas','Missionárias e Comunitárias'),
	('Pregador Evangelista','Missionárias e Comunitárias'),
	('Pregador Evangelista - avançado','Missionárias e Comunitárias'),
	('Santuário','Missionárias e Comunitárias'),
	('Sonoplastia','Missionárias e Comunitárias'),
	('Sonoplastia - avançado','Missionárias e Comunitárias'),
	('Temperança','Missionárias e Comunitárias'),
	('Testemunho Juvenil','Missionárias e Comunitárias'),
	('Vida Familiar','Missionárias e Comunitárias'),
	('Administração','Atividades Profissionais'),
	('Alvenaria','Atividades Profissionais'),
	('Bandeiras Náuticas','Atividades Profissionais'),
	('Barbearia','Atividades Profissionais'),
	('Biblioteconomia','Atividades Profissionais'),
	('Blogs','Atividades Profissionais'),
	('Cães - Cuidado e Treinamento','Atividades Profissionais'),
	('Carpintaria','Atividades Profissionais'),
	('Código Morse','Atividades Profissionais'),
	('Código Semafórico','Atividades Profissionais'),
	('Colocação de Papel de Parede','Atividades Profissionais'),
	('Computação III - regular','Atividades Profissionais'),
	('Computação II - médio','Atividades Profissionais'),
	('Computação IV - avançado','Atividades Profissionais'),
	('Computação I - básico','Atividades Profissionais'),
	('Computação V - especialista','Atividades Profissionais'),
	('Conserto de Sapatos','Atividades Profissionais'),
	('Contabilidade','Atividades Profissionais'),
	('Corte e Costura','Atividades Profissionais'),
	('Corte e Costura - avançado','Atividades Profissionais'),
	('Cuidados e Manutenção de Violões','Atividades Profissionais'),
	('Datilografia','Atividades Profissionais'),
	('Desenvolvimento de Software','Atividades Profissionais'),
	('Eletricidade','Atividades Profissionais'),
	('Eletrônica','Atividades Profissionais'),
	('Encadernação','Atividades Profissionais'),
	('Evangelismo','Atividades Profissionais'),
	('Fotografia','Atividades Profissionais'),
	('Hidráulica','Atividades Profissionais'),
	('Informática Programável','Atividades Profissionais'),
	('Internet','Atividades Profissionais'),
	('Internet - avançado','Atividades Profissionais'),
	('Intérprete de Língua de Sinais','Atividades Profissionais'),
	('Jornalismo','Atividades Profissionais'),
	('Magistério','Atividades Profissionais'),
	('Manutenção de Bicicletas','Atividades Profissionais'),
	('Marcenaria','Atividades Profissionais'),
	('Marketing','Atividades Profissionais'),
	('Marketing - avançado','Atividades Profissionais'),
	('Mecânica Automotiva','Atividades Profissionais'),
	('Mecânica Automotiva - avançado','Atividades Profissionais'),
	('Mecânica de Pequenos Motores','Atividades Profissionais'),
	('Modelagem Têxtil','Atividades Profissionais'),
	('Montagem e Manutenção de Computadores','Atividades Profissionais'),
	('Noções de Economia','Atividades Profissionais'),
	('Ofício de Alfaiate','Atividades Profissionais'),
	('Operação e Manutenção de Impressoras','Atividades Profissionais'),
	('Pintura de Paredes Exteriores','Atividades Profissionais'),
	('Pintura de Paredes Interiores','Atividades Profissionais'),
	('Produção de Vídeo','Atividades Profissionais'),
	('Radioamadorismo','Atividades Profissionais'),
	('Radioamadorismo - avançado','Atividades Profissionais'),
	('Radioeletrônica','Atividades Profissionais'),
	('Restauro e Conservação Documental','Atividades Profissionais'),
	('Secretariado','Atividades Profissionais'),
	('Serviço Rádio do Cidadão','Atividades Profissionais'),
	('Silvicultura','Atividades Profissionais'),
	('Soldagem','Atividades Profissionais'),
	('Taquigrafia','Atividades Profissionais'),
	('Tipografia','Atividades Profissionais'),
	('Torno Mecânico','Atividades Profissionais'),
	('Vendas','Atividades Profissionais'),
	('Web Design - avançado','Atividades Profissionais'),
	('Web Design - básico','Atividades Profissionais'),
	('Acampamento em Baixas Temperaturas','Atividades Recreativas'),
	('Acampamento I','Atividades Recreativas'),
	('Acampamento II','Atividades Recreativas'),
	('Acampamento III','Atividades Recreativas'),
	('Acampamento IV','Atividades Recreativas'),
	('Acampamento Seguro','Atividades Recreativas'),
	('Acampamento Seguro - avançado','Atividades Recreativas'),
	('Arco e Flecha','Atividades Recreativas'),
	('Arco e Flecha - avançado','Atividades Recreativas'),
	('Arte de Acampar','Atividades Recreativas'),
	('Atletismo','Atividades Recreativas'),
	('Barco a Motor','Atividades Recreativas'),
	('Basquete','Atividades Recreativas'),
	('Boliche','Atividades Recreativas'),
	('Caiaque','Atividades Recreativas'),
	('Campori Seguro','Atividades Recreativas'),
	('Canoagem','Atividades Recreativas'),
	('Carrinho de Rolimã','Atividades Recreativas'),
	('Ciclismo','Atividades Recreativas'),
	('Ciclismo - avançado','Atividades Recreativas'),
	('Colecionador','Atividades Recreativas'),
	('Construção de Canoas','Atividades Recreativas'),
	('Cozinha com Forno Holandês','Atividades Recreativas'),
	('Cultura Física','Atividades Recreativas'),
	('Equitação','Atividades Recreativas'),
	('Equitação - avançado','Atividades Recreativas'),
	('Escalada','Atividades Recreativas'),
	('Escalada - avançado','Atividades Recreativas'),
	('Escalada em Árvores','Atividades Recreativas'),
	('Esportes Adaptados','Atividades Recreativas'),
	('Esqui Aquático','Atividades Recreativas'),
	('Esqui Aquático - avançado','Atividades Recreativas'),
	('Esqui Cross Country','Atividades Recreativas'),
	('Esqui Downhill','Atividades Recreativas'),
	('Evolução em Ordem Unida','Atividades Recreativas'),
	('Excursionismo Pedestre','Atividades Recreativas'),
	('Excursionismo Pedestre - avançado','Atividades Recreativas'),
	('Excursionismo Pedestre com Mochila','Atividades Recreativas'),
	('Excursionismo Pedestre com Mochila - avançado','Atividades Recreativas'),
	('Excursionismo Pedestre na Neve','Atividades Recreativas'),
	('Excursionismo Pedestre na Neve - avançado','Atividades Recreativas'),
	('Exploração de Cavernas','Atividades Recreativas'),
	('Exploração de Cavernas - avançado','Atividades Recreativas'),
	('Fanfarra','Atividades Recreativas'),
	('Filatelia','Atividades Recreativas'),
	('Filatelia - avançado','Atividades Recreativas'),
	('Fogueiras e Cozinha ao Ar Livre','Atividades Recreativas'),
	('Futebol','Atividades Recreativas'),
	('Futebol de Botão','Atividades Recreativas'),
	('Futsal','Atividades Recreativas'),
	('Geocaching','Atividades Recreativas'),
	('Geocaching - avançado','Atividades Recreativas'),
	('Ginástica Acrobática','Atividades Recreativas'),
	('Ginástica Acrobática - avançado','Atividades Recreativas'),
	('Handebol','Atividades Recreativas'),
	('Letterboxing','Atividades Recreativas'),
	('Letterboxing - avançado','Atividades Recreativas'),
	('Liderança Campestre','Atividades Recreativas'),
	('Liderança Campestre - avançado','Atividades Recreativas'),
	('Liderança na Selva','Atividades Recreativas'),
	('Liderança na Selva - avançado','Atividades Recreativas'),
	('Mapa e Bússola','Atividades Recreativas'),
	('Mergulho Autônomo','Atividades Recreativas'),
	('Mergulho Autônomo - avançado','Atividades Recreativas'),
	('Mergulho Livre','Atividades Recreativas'),
	('Monociclo','Atividades Recreativas'),
	('Mountain Biking','Atividades Recreativas'),
	('Natação - avançado','Atividades Recreativas'),
	('Natação Intermediário I','Atividades Recreativas'),
	('Natação Intermediário II','Atividades Recreativas'),
	('Natação Principiante I','Atividades Recreativas'),
	('Natação Principiante II','Atividades Recreativas'),
	('Navegação','Atividades Recreativas'),
	('Nós e Amarras','Atividades Recreativas'),
	('Nós e Amarras - avançado','Atividades Recreativas'),
	('Numismática','Atividades Recreativas'),
	('Numismática - avançado','Atividades Recreativas'),
	('Ordem Unida','Atividades Recreativas'),
	('Ordem Unida - avançado','Atividades Recreativas'),
	('Ordem Unida - instrutor','Atividades Recreativas'),
	('Orientação com GPS','Atividades Recreativas'),
	('Patins','Atividades Recreativas'),
	('Pião','Atividades Recreativas'),
	('Pioneirias','Atividades Recreativas'),
	('Pioneirias - avançado','Atividades Recreativas'),
	('Pioneirismo','Atividades Recreativas'),
	('Pipas','Atividades Recreativas'),
	('Rafting','Atividades Recreativas'),
	('Rapel','Atividades Recreativas'),
	('Rapel - avançado','Atividades Recreativas'),
	('Rapel - instrutor','Atividades Recreativas'),
	('Remo','Atividades Recreativas'),
	('Saltos Ornamentais','Atividades Recreativas'),
	('Salvamento de Afogados','Atividades Recreativas'),
	('Salvamento de Afogados - avançado','Atividades Recreativas'),
	('Segurança Básica na Água','Atividades Recreativas'),
	('Skate','Atividades Recreativas'),
	('Softbol','Atividades Recreativas'),
	('Telecartofilia','Atividades Recreativas'),
	('Telecartofilia - avançado','Atividades Recreativas'),
	('Tênis de Mesa','Atividades Recreativas'),
	('Triathlon','Atividades Recreativas'),
	('Triathlon - avançado','Atividades Recreativas'),
	('Vela','Atividades Recreativas'),
	('Viagem e Turismo','Atividades Recreativas'),
	('Viagem e Turismo - avançado','Atividades Recreativas'),
	('Vida Silvestre','Atividades Recreativas'),
	('Vôlei','Atividades Recreativas'),
	('Wakeboard','Atividades Recreativas'),
	('Waveboarding','Atividades Recreativas'),
	('Windsurf','Atividades Recreativas'),
	('Alerta Vermelho','Ciência e Saúde'),
	('Bioquímica','Ciência e Saúde'),
	('Bioquímica - avançado','Ciência e Saúde'),
	('Biossegurança','Ciência e Saúde'),
	('Coração e Circulação','Ciência e Saúde'),
	('Digestão','Ciência e Saúde'),
	('Enfermagem Básica','Ciência e Saúde'),
	('Física','Ciência e Saúde'),
	('Habilidades em Matemática I','Ciência e Saúde'),
	('Habilidades em Matemática II','Ciência e Saúde'),
	('Habilidades em Matemática III','Ciência e Saúde'),
	('Habilidades em Matemática IV','Ciência e Saúde'),
	('Hereditariedade','Ciência e Saúde'),
	('Higiene Oral','Ciência e Saúde'),
	('Higiene Oral - avançado','Ciência e Saúde'),
	('Metodologia de Estudo','Ciência e Saúde'),
	('Microscopia','Ciência e Saúde'),
	('Nutrição','Ciência e Saúde'),
	('Nutrição - avançado','Ciência e Saúde'),
	('Ossos Músculos e Articulações','Ciência e Saúde'),
	('Ótica','Ciência e Saúde'),
	('Patrimônio Histórico','Ciência e Saúde'),
	('Prevenção de Doenças Tropicais','Ciência e Saúde'),
	('Primeiros Socorros - intermediário','Ciência e Saúde'),
	('Química','Ciência e Saúde'),
	('Reanimação Cardiopulmonar','Ciência e Saúde'),
	('Resgate Básico','Ciência e Saúde'),
	('Sangue e Defesas do Corpo','Ciência e Saúde'),
	('Saúde e Cura','Ciência e Saúde'),
	('Saúde Mental','Ciência e Saúde'),
	('Sexualidade Humana','Ciência e Saúde'),
	('Sistema Nervoso','Ciência e Saúde'),
	('Sistema Respiratório','Ciência e Saúde'),
	('Algas','Estudos da Natureza'),
	('Anfíbios','Estudos da Natureza'),
	('Anfíbios - avançado','Estudos da Natureza'),
	('Animais Ameaçados de Extinção','Estudos da Natureza'),
	('Animais Nocivos','Estudos da Natureza'),
	('Animais Noturnos','Estudos da Natureza'),
	('Animais Peçonhentos','Estudos da Natureza'),
	('Aquarismo','Estudos da Natureza'),
	('Aranhas','Estudos da Natureza'),
	('Araras, Papagaios e Periquitos','Estudos da Natureza'),
	('Arbustos','Estudos da Natureza'),
	('Arbustos - avançado','Estudos da Natureza'),
	('Areia','Estudos da Natureza'),
	('Árvores','Estudos da Natureza'),
	('Árvores - avançado','Estudos da Natureza'),
	('Astronomia','Estudos da Natureza'),
	('Astronomia - avançado','Estudos da Natureza'),
	('Aves','Estudos da Natureza'),
	('Aves - avançado','Estudos da Natureza'),
	('Aves de Estimação','Estudos da Natureza'),
	('Aves Domésticas','Estudos da Natureza'),
	('Bactérias','Estudos da Natureza'),
	('Briófitas','Estudos da Natureza'),
	('Cactos','Estudos da Natureza'),
	('Cactos - avançado','Estudos da Natureza'),
	('Cães','Estudos da Natureza'),
	('Camelos','Estudos da Natureza'),
	('Cetáceos','Estudos da Natureza'),
	('Citologia','Estudos da Natureza'),
	('Climatologia','Estudos da Natureza'),
	('Climatologia - avançado','Estudos da Natureza'),
	('Conservação Ambiental','Estudos da Natureza'),
	('Crustáceos','Estudos da Natureza'),
	('Dinossauros','Estudos da Natureza'),
	('Ecologia','Estudos da Natureza'),
	('Ecologia - avançado','Estudos da Natureza'),
	('Energias Renováveis','Estudos da Natureza'),
	('Equinodermos','Estudos da Natureza'),
	('Ervas','Estudos da Natureza'),
	('Estuário','Estudos da Natureza'),
	('Eucaliptos','Estudos da Natureza'),
	('Fauna Marinha','Estudos da Natureza'),
	('Felinos','Estudos da Natureza'),
	('Felinos - avançado','Estudos da Natureza'),
	('Fisiologia Vegetal','Estudos da Natureza'),
	('Flores','Estudos da Natureza'),
	('Flores - avançado','Estudos da Natureza'),
	('Formigas','Estudos da Natureza'),
	('Fósseis','Estudos da Natureza'),
	('Fungos','Estudos da Natureza'),
	('Geologia','Estudos da Natureza'),
	('Geologia - avançado','Estudos da Natureza'),
	('Gramíneas','Estudos da Natureza'),
	('Insetos','Estudos da Natureza'),
	('Insetos - avançado','Estudos da Natureza'),
	('Liquens','Estudos da Natureza'),
	('Mamíferos','Estudos da Natureza'),
	('Mamíferos - avançado','Estudos da Natureza'),
	('Mamíferos Marinhos','Estudos da Natureza'),
	('Mariposas e Borboletas','Estudos da Natureza'),
	('Marsupiais','Estudos da Natureza'),
	('Moluscos','Estudos da Natureza'),
	('Moluscos - avançado','Estudos da Natureza'),
	('Morcegos','Estudos da Natureza'),
	('Morcegos - avançado','Estudos da Natureza'),
	('Odonata','Estudos da Natureza'),
	('Orquídeas','Estudos da Natureza'),
	('Orquídeas - avançado','Estudos da Natureza'),
	('Palmeiras','Estudos da Natureza'),
	('Peixes','Estudos da Natureza'),
	('Pequenos Mamíferos de Estimação','Estudos da Natureza'),
	('Plantas Carnívoras','Estudos da Natureza'),
	('Plantas Caseiras','Estudos da Natureza'),
	('Plantas Silvestres Comestíveis','Estudos da Natureza'),
	('Poríferos e Cnidários','Estudos da Natureza'),
	('Preservação de Recursos Hídricos','Estudos da Natureza'),
	('Protozoários','Estudos da Natureza'),
	('Quedas dágua','Estudos da Natureza'),
	('Rastreio de Animais','Estudos da Natureza'),
	('Rastreio de Animais - avançado','Estudos da Natureza'),
	('Rebanhos Domésticos','Estudos da Natureza'),
	('Reciclagem e Sustentabilidade','Estudos da Natureza'),
	('Reciclagem e Sustentabilidade - avançado','Estudos da Natureza'),
	('Répteis','Estudos da Natureza'),
	('Répteis - avançado','Estudos da Natureza'),
	('Rochas e minerais','Estudos da Natureza'),
	('Rochas e Minerais - avançado','Estudos da Natureza'),
	('Samambaias','Estudos da Natureza'),
	('Sementes','Estudos da Natureza'),
	('Sementes - avançado','Estudos da Natureza'),
	('Solos','Estudos da Natureza'),
	('Tubarões','Estudos da Natureza'),
	('Vermes','Estudos da Natureza'),
	('Vermes - avançado','Estudos da Natureza'),
	('Vírus','Estudos da Natureza'),
	('Arte Culinária','Habilidades Domésticas'),
	('Arte Culinária - avançado','Habilidades Domésticas'),
	('Comidas Típicas','Habilidades Domésticas'),
	('Congelamento de Alimentos','Habilidades Domésticas'),
	('Costura Básica','Habilidades Domésticas'),
	('Cuidados da Casa','Habilidades Domésticas'),
	('Cuidado de Bebês','Habilidades Domésticas'),
	('Desidratação de Alimentos','Habilidades Domésticas'),
	('Orçamento Familiar','Habilidades Domésticas'),
	('Panificação','Habilidades Domésticas'),
	('Técnicas de Fazer Conserva','Habilidades Domésticas'),
	('Técnicas de Lavanderia','Habilidades Domésticas'),
	('Mestrado em ADRA','Mestrados'),
	('Mestrado em Aquática','Mestrados'),
	('Mestrado em Artes e Habilidades Manuais','Mestrados'),
	('Mestrado em Atividades Agrícolas','Mestrados'),
	('Mestrado em Atividades Profissionais','Mestrados'),
	('Mestrado em Atividades Recreativas','Mestrados'),
	('Mestrado em Botânica','Mestrados'),
	('Mestrado em Ciência e Tecnologia','Mestrados'),
	('Mestrado em Ecologia','Mestrados'),
	('Mestrado em Esportes','Mestrados'),
	('Mestrado em Habilidades Domésticas','Mestrados'),
	('Mestrado em Saúde','Mestrados'),
	('Mestrado em Testificação','Mestrados'),
	('Mestrado em Vida Campestre','Mestrados'),
	('Mestrado em Zoologia','Mestrados');